const config = {
  apiUrl: import.meta.env.VITE_API_SERVER_URL,
  testToken:
    "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjdmTVg5SEhMVnNIZmpSNC04YXA5QiJ9.eyJpc3MiOiJodHRwczovL2Rldi03dW40ZGhmYng0aHhkcDE4LnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw2M2ZkZTBiODdhZTFkM2Q0N2MwNzVmNzgiLCJhdWQiOiJVZGFjaXR5Q29mZmVlc2hvcCIsImlhdCI6MTY3ODIxMDQ0OSwiZXhwIjoxNjc4MjE3NjQ5LCJhenAiOiJ6alBiTkdFNXJaVElWenM5YnlYNUlHUTZPcEJyQkU1SiIsInNjb3BlIjoiIiwicGVybWlzc2lvbnMiOlsiZGVsZXRlOmRyaW5rcyIsImdldDpkcmlua3MiLCJnZXQ6ZHJpbmtzLWRldGFpbCIsInBhdGNoOmRyaW5rcyIsInBvc3Q6ZHJpbmtzIl19.qAL6-Zz889Jl-jvOZhcX9vUlmLoVOFAtcRj7n-_KwUUqeZgoX1BG0o1uHxYpmrFaE3TGkXhEWK_Hh_ItuA8Yd42Kq2P3E_1TYo0CnZFrbwQtk2DSNgD1aYnukl2ofUi9Q8kJlka2a3C4Ln8kNQ66wY4maRM3Uv0I_Nag2FkZ7yAtcl3doO_07fke8-AXWunrPZ7hpT04ZEDfISkubQLUxixFSiTmRY0fLgp2S9zFaVJZxtjil4YusoMSq-hup9lzhwFMSSIbymibd7uKbDuyH3nIEPTw74EXrFjLkmOztQvn9zYya5rbIZ_lZbzX2fA_iYZ458Y6c-P-j4XD6u8oSA",
  domain: import.meta.env.VITE_AUTH0_DOMAIN,
  clientId: import.meta.env.VITE_AUTH0_CLIENT_ID,
  audience: import.meta.env.VITE_AUTH0_API_AUDIENCE,
  callbackUrl: import.meta.env.VITE_AUTH0_CALLBACK_URL,
}

export default config
